spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 100

local: messagelocal

server:
  port: 8081

messagehub:
  port: 5004
  address: 0.0.0.0
  pool:
    maxqueuecount: 5


eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin@10.1.1.114:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    appname: MessageHub
    instanceId: MessageHub:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true

zuul: # those values must be configured depending on the application specific needs
    host:
        max-total-connections: 1000
        max-per-route-connections: 100
    semaphore:
        max-semaphores: 500







