spring:
  redis:
    database: 0
    host: 119.23.136.251
    port: 6379
    timeout: 100

local: messagelocal

server:
  port: 8081

messagehub:
  port: 5004
  address: 0.0.0.0


#eureka:
#    instance:
#        hostname: messagehubjava
#    client:
#        service-url:
#            defaultZone: http://admin:admin@10.1.1.121:8761/eureka/