spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 100

local: messagelocal

server:
  port: 8081

messagehub:
  port: 5004
  address: 0.0.0.0
  pool:
    maxqueuecount: 5


